micronaut:
  application:
    name: storefront
  server:
    port: 8081
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths:
          - classpath:/static